# Generated by Django 4.1.2 on 2022-10-19 08:35

import colorfield.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("GA", "General"),
                            ("CA", "Cash"),
                            ("CU", "Current"),
                            ("SA", "Savings"),
                            ("IS", "Insurance"),
                            ("IV", "Investment"),
                            ("CC", "Credit Card"),
                            ("LO", "Loan"),
                        ],
                        default="GA",
                        max_length=2,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Balance"
                    ),
                ),
                (
                    "balance_can_be_negative",
                    models.BooleanField(
                        default=False, verbose_name="Balance can be negative"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "exclude_from_budget",
                    models.BooleanField(
                        default=False, verbose_name="Exclude from budget"
                    ),
                ),
                (
                    "show_on_dashboard",
                    models.BooleanField(default=True, verbose_name="Show on Dashboard"),
                ),
                (
                    "color_on_dashboard",
                    colorfield.fields.ColorField(
                        default="#7DD181",
                        image_field=None,
                        max_length=18,
                        samples=[
                            ("#7DD181", "Mantis"),
                            ("#16DB65", "Malachite"),
                            ("#51CB20", "Lime Green"),
                            ("#BDD358", "June Bud"),
                            ("#68A357", "Asparagus"),
                            ("#32965D", "Green Cyan"),
                            ("#09814A", "Sea Green"),
                            ("#317B22", "Ao English"),
                            ("#F1A7A9", "Pastel Pink"),
                            ("#EC8385", "Light Coral"),
                            ("#E66063", "Fuzzy Wuzzy"),
                            ("#E35053", "Indian Red"),
                            ("#FF3C38", "Tart Orange"),
                            ("#E3170A", "Vermilion"),
                            ("#BD1F21", "Firebrick"),
                            ("#9C191B", "Ruby Red"),
                            ("#F95738", "Orange Soda"),
                            ("#D34E24", "Sinopia"),
                            ("#EC9A29", "Carrot Orange"),
                            ("#FF8C42", "Mango Tango"),
                            ("#EE6352", "Fire Opal"),
                            ("#F56476", "Fiery Rose"),
                            ("#E87461", "Terra Cotta"),
                            ("#E5C687", "Gold Crayola"),
                            ("#FAC9B8", "Apricot"),
                            ("#A1E8CC", "Magic Mint"),
                            ("#41E2BA", "Medium Aquamarine"),
                            ("#0F8B8D", "Dark Cyan"),
                            ("#85C7F2", "Light Sky Blue"),
                            ("#A1B5D8", "Wild Blue Yonder"),
                            ("#805D93", "French Lilac"),
                            ("#6F73D2", "Violet Blue Crayola"),
                        ],
                        verbose_name="Color on Dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ["-active", "name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("IN", "Income"),
                            ("EX", "Expense"),
                            ("TR", "Transfer"),
                        ],
                        default="EX",
                        max_length=2,
                        verbose_name="Category group",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["group", "name"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("symbol", models.CharField(max_length=5, verbose_name="Symbol")),
                ("code", models.CharField(max_length=3, verbose_name="Code")),
                (
                    "decimal_places",
                    models.IntegerField(default=2, verbose_name="Digits"),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("IN", "Income"),
                            ("EX", "Expense"),
                            ("TR", "Transfer"),
                        ],
                        default="EX",
                        max_length=2,
                        verbose_name="Transaction type",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="core.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "dest_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.account",
                        verbose_name="Transfer destination account",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(
                        choices=[("WE", "Week"), ("MN", "Month"), ("YR", "Year")],
                        default="MN",
                        max_length=2,
                        verbose_name="Period",
                    ),
                ),
                ("start_day", models.DateField(verbose_name="Start day")),
                ("end_day", models.DateField(verbose_name="End day")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.category",
                        verbose_name="Budget category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.transaction",),
            managers=[
                ("onjects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Income",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.transaction",),
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.transaction",),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("name", "account_type")},
        ),
    ]
