# Generated by Django 4.1.2 on 2022-10-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="transaction_type",
            new_name="type",
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="currency",
            name="decimal_places",
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("GA", "General"),
                    ("CA", "Cash"),
                    ("CU", "Current"),
                    ("SA", "Savings"),
                    ("IS", "Insurance"),
                    ("IV", "Investment"),
                    ("CC", "Credit Card"),
                    ("LO", "Loan"),
                ],
                default="GA",
                max_length=2,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Balance"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Budgeted mount",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("name", "type")},
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_type",
        ),
    ]
