#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

python /app/manage.py collectstatic --noinput
python /app/manage.py makemigrations
python /app/manage.py migrate

/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:80 --chdir=/app
