# Generated by Django 4.0.10 on 2023-03-10 14:52

import colorfield.fields
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('account_type', models.CharField(choices=[('GA', 'General'), ('CA', 'Cash'), ('CU', 'Current'), ('SA', 'Savings'), ('IS', 'Insurance'), ('IV', 'Investment'), ('CC', 'Credit Card'), ('LO', 'Loan')], default='GA', max_length=2, verbose_name='Type')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance')),
                ('balance_can_be_negative', models.BooleanField(default=False, verbose_name='Balance can be negative')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('exclude_from_budget', models.BooleanField(default=False, verbose_name='Exclude from budget')),
                ('show_on_dashboard', models.BooleanField(default=True, verbose_name='Show on Dashboard')),
                ('color', colorfield.fields.ColorField(default='#7DD181', image_field=None, max_length=18, samples=[('#FDE8E8', 'red-100'), ('#FBD5D5', 'red-200'), ('#F8B4B4', 'red-300'), ('#F98080', 'red-400'), ('#F05252', 'red-500'), ('#E02424', 'red-600'), ('#C81E1E', 'red-700'), ('#9B1C1C', 'red-800'), ('#FDF6B2', 'yellow-100'), ('#FCE96A', 'yellow-200'), ('#FACA15', 'yellow-300'), ('#E3A008', 'yellow-400'), ('#C27803', 'yellow-500'), ('#9F580A', 'yellow-600'), ('#8E4B10', 'yellow-700'), ('#723B13', 'yellow-800'), ('#DEF7EC', 'green-100'), ('#BCF0DA', 'green-200'), ('#84E1BC', 'green-300'), ('#31C48D', 'green-400'), ('#0E9F6E', 'green-500'), ('#057A55', 'green-600'), ('#046C4E', 'green-700'), ('#03543F', 'green-800'), ('#E1EFFE', 'blue-100'), ('#C3DDFD', 'blue-200'), ('#A4CAFE', 'blue-300'), ('#76A9FA', 'blue-400'), ('#3F83F8', 'blue-500'), ('#1C64F2', 'blue-600'), ('#1A56DB', 'blue-700'), ('#1E429F', 'blue-800'), ('#E5EDFF', 'indigo-100'), ('#CDDBFE', 'indigo-200'), ('#B4C6FC', 'indigo-300'), ('#8DA2FB', 'indigo-400'), ('#6875F5', 'indigo-500'), ('#5850EC', 'indigo-600'), ('#5145CD', 'indigo-700'), ('#42389D', 'indigo-800'), ('#EDEBFE', 'purple-100'), ('#DCD7FE', 'purple-200'), ('#CABFFD', 'purple-300'), ('#AC94FA', 'purple-400'), ('#9061F9', 'purple-500'), ('#7E3AF2', 'purple-600'), ('#6C2BD9', 'purple-700'), ('#5521B5', 'purple-800'), ('#FDF2F8', 'pink-100'), ('#FAD1E8', 'pink-200'), ('#F8B4D9', 'pink-300'), ('#F17EB8', 'pink-400'), ('#E74694', 'pink-500'), ('#D61F69', 'pink-600'), ('#BF125D', 'pink-700'), ('#99154B', 'pink-800'), ('#7DD181', 'Mantis'), ('#16DB65', 'Malachite'), ('#51CB20', 'Lime Green'), ('#BDD358', 'June Bud'), ('#68A357', 'Asparagus'), ('#32965D', 'Green Cyan'), ('#09814A', 'Sea Green'), ('#317B22', 'Ao English'), ('#F1A7A9', 'Pastel Pink'), ('#EC8385', 'Light Coral'), ('#E66063', 'Fuzzy Wuzzy'), ('#E35053', 'Indian Red'), ('#FF3C38', 'Tart Orange'), ('#E3170A', 'Vermilion'), ('#BD1F21', 'Firebrick'), ('#9C191B', 'Ruby Red'), ('#F95738', 'Orange Soda'), ('#D34E24', 'Sinopia'), ('#EC9A29', 'Carrot Orange'), ('#FF8C42', 'Mango Tango'), ('#EE6352', 'Fire Opal'), ('#F56476', 'Fiery Rose'), ('#E87461', 'Terra Cotta'), ('#E5C687', 'Gold Crayola'), ('#FAC9B8', 'Apricot'), ('#A1E8CC', 'Magic Mint'), ('#41E2BA', 'Medium Aquamarine'), ('#0F8B8D', 'Dark Cyan'), ('#85C7F2', 'Light Sky Blue'), ('#A1B5D8', 'Wild Blue Yonder'), ('#805D93', 'French Lilac'), ('#6F73D2', 'Violet Blue Crayola')], verbose_name='Color on Dashboard')),
                ('text_color', models.CharField(blank=True, editable=False, max_length=12, verbose_name='Text color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-active', 'name'],
                'unique_together': {('name', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Budgeted mount')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Actual amount')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense'), ('TR', 'Transfer')], default='EX', max_length=2, verbose_name='Category group')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('active', models.BooleanField(default=True)),
                ('color', colorfield.fields.ColorField(default='#7DD181', image_field=None, max_length=18, samples=[('#FDE8E8', 'red-100'), ('#FBD5D5', 'red-200'), ('#F8B4B4', 'red-300'), ('#F98080', 'red-400'), ('#F05252', 'red-500'), ('#E02424', 'red-600'), ('#C81E1E', 'red-700'), ('#9B1C1C', 'red-800'), ('#FDF6B2', 'yellow-100'), ('#FCE96A', 'yellow-200'), ('#FACA15', 'yellow-300'), ('#E3A008', 'yellow-400'), ('#C27803', 'yellow-500'), ('#9F580A', 'yellow-600'), ('#8E4B10', 'yellow-700'), ('#723B13', 'yellow-800'), ('#DEF7EC', 'green-100'), ('#BCF0DA', 'green-200'), ('#84E1BC', 'green-300'), ('#31C48D', 'green-400'), ('#0E9F6E', 'green-500'), ('#057A55', 'green-600'), ('#046C4E', 'green-700'), ('#03543F', 'green-800'), ('#E1EFFE', 'blue-100'), ('#C3DDFD', 'blue-200'), ('#A4CAFE', 'blue-300'), ('#76A9FA', 'blue-400'), ('#3F83F8', 'blue-500'), ('#1C64F2', 'blue-600'), ('#1A56DB', 'blue-700'), ('#1E429F', 'blue-800'), ('#E5EDFF', 'indigo-100'), ('#CDDBFE', 'indigo-200'), ('#B4C6FC', 'indigo-300'), ('#8DA2FB', 'indigo-400'), ('#6875F5', 'indigo-500'), ('#5850EC', 'indigo-600'), ('#5145CD', 'indigo-700'), ('#42389D', 'indigo-800'), ('#EDEBFE', 'purple-100'), ('#DCD7FE', 'purple-200'), ('#CABFFD', 'purple-300'), ('#AC94FA', 'purple-400'), ('#9061F9', 'purple-500'), ('#7E3AF2', 'purple-600'), ('#6C2BD9', 'purple-700'), ('#5521B5', 'purple-800'), ('#FDF2F8', 'pink-100'), ('#FAD1E8', 'pink-200'), ('#F8B4D9', 'pink-300'), ('#F17EB8', 'pink-400'), ('#E74694', 'pink-500'), ('#D61F69', 'pink-600'), ('#BF125D', 'pink-700'), ('#99154B', 'pink-800'), ('#7DD181', 'Mantis'), ('#16DB65', 'Malachite'), ('#51CB20', 'Lime Green'), ('#BDD358', 'June Bud'), ('#68A357', 'Asparagus'), ('#32965D', 'Green Cyan'), ('#09814A', 'Sea Green'), ('#317B22', 'Ao English'), ('#F1A7A9', 'Pastel Pink'), ('#EC8385', 'Light Coral'), ('#E66063', 'Fuzzy Wuzzy'), ('#E35053', 'Indian Red'), ('#FF3C38', 'Tart Orange'), ('#E3170A', 'Vermilion'), ('#BD1F21', 'Firebrick'), ('#9C191B', 'Ruby Red'), ('#F95738', 'Orange Soda'), ('#D34E24', 'Sinopia'), ('#EC9A29', 'Carrot Orange'), ('#FF8C42', 'Mango Tango'), ('#EE6352', 'Fire Opal'), ('#F56476', 'Fiery Rose'), ('#E87461', 'Terra Cotta'), ('#E5C687', 'Gold Crayola'), ('#FAC9B8', 'Apricot'), ('#A1E8CC', 'Magic Mint'), ('#41E2BA', 'Medium Aquamarine'), ('#0F8B8D', 'Dark Cyan'), ('#85C7F2', 'Light Sky Blue'), ('#A1B5D8', 'Wild Blue Yonder'), ('#805D93', 'French Lilac'), ('#6F73D2', 'Violet Blue Crayola')], verbose_name='Color on Dashboard')),
                ('text_color', models.CharField(blank=True, editable=False, max_length=12, verbose_name='Text color')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('AUD', 'Australia Dollar'), ('CAD', 'Canada Dollar'), ('¥', 'China Yuan Renminbi'), ('€', 'Euro Member Countries'), ('lei', 'Romania Leu'), ('£', 'United Kingdom Pound'), ('$', 'United States Dollar')], default='$', max_length=3)),
                ('start_date_of_month', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31, message='Value must be between 1 and 31.'), django.core.validators.MinValueValidator(1, message='Value must be between 1 and 31.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('transaction_type', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense'), ('TR', 'Transfer')], max_length=2, verbose_name='Transaction type')),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.account', verbose_name='Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.category', verbose_name='Category')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account', verbose_name='Transfer destination account')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.category')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
