# Generated by Django 4.0.10 on 2023-03-16 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='start_date_of_month',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='start_day_of_month',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(28, message='Value must be between 1 and 28.'), django.core.validators.MinValueValidator(1, message='Value must be between 1 and 28.')]),
        ),
    ]
