# Generated by Django 4.0.10 on 2023-03-23 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0005_alter_category_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField()),
                ('last_day', models.DateField(blank=True)),
                ('month_code', models.PositiveSmallIntegerField(blank=True, editable=False)),
                ('override_last_day', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'unique_together': {('user', 'month_code')},
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-active', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='budget',
            name='actual_amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(related_name='budgets', to='wallet.category'),
        ),
        migrations.DeleteModel(
            name='BudgetItem',
        ),
    ]
