# Generated by Django 4.0.10 on 2023-03-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_month_alter_account_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='start_date',
        ),
        migrations.AddField(
            model_name='budget',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='wallet.month'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='budgeted_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budgeted mount'),
        ),
    ]
