# Generated by Django 4.0.10 on 2023-03-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_remove_budget_end_date_remove_budget_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='wallet.month', verbose_name='Month'),
        ),
    ]
