# Generated by Django 4.0.10 on 2023-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_budget_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Is recurring'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('MO', 'Monthly'), ('QU', 'Quarterly'), ('BI', 'Biannualy'), ('AN', 'Annualy')], max_length=2, verbose_name='Recurrence'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense'), ('TR', 'Transfer'), ('AD', 'Balance Adjustment')], max_length=2, verbose_name='Transaction type'),
        ),
    ]
