# Generated by Django 4.0.10 on 2023-03-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_transaction_is_recurring_transaction_recurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_planned',
            field=models.BooleanField(default=False, verbose_name='Is planned'),
        ),
    ]
