# Generated by Django 4.0.10 on 2023-03-25 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_remove_transaction_is_recurring_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='recurrence',
            new_name='recurrence_frequency',
        ),
    ]
