# Generated by Django 4.0.10 on 2023-03-26 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_rename_recurrence_transaction_recurrence_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_planned',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurrent',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recurrence_frequency',
        ),
        migrations.CreateModel(
            name='PlannedTransaction',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('transaction_type', models.CharField(choices=[('IN', 'Income'), ('EX', 'Expense')], max_length=2, verbose_name='Transaction type')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('MO', 'Monthly'), ('QU', 'Quarterly'), ('BI', 'Biannualy'), ('AN', 'Annualy')], max_length=2, null=True)),
                ('recurrence_id', models.UUIDField(blank=True, null=True)),
                ('is_duplicated', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_transactions', to='wallet.account', verbose_name='Account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_transactions', to='wallet.category', verbose_name='Category')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account', verbose_name='Transfer destination account')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
