# Generated by Django 4.0.10 on 2023-04-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_alter_budget_options_remove_budget_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['group', 'parent__id', 'id'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Name'),
        ),
    ]
