# Generated by Django 4.0.10 on 2023-04-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_alter_category_options_alter_budget_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_decimal_places',
            field=models.BooleanField(default=True),
        ),
    ]
