# Generated by Django 4.0.10 on 2023-04-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_usersettings_show_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budgeted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budgeted mount'),
        ),
    ]
