# Generated by Django 4.0.10 on 2023-04-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_alter_budget_budgeted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='root_category',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_subcategories', to='wallet.category'),
        ),
    ]
