# Generated by Django 4.0.10 on 2023-04-07 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0020_category_root_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ('-first_day',)},
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_category_month',
        ),
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_master_month',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'month'), ('user', 'is_master', 'month')},
        ),
    ]
