# Generated by Django 4.0.10 on 2023-04-09 17:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0021_alter_month_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'month')},
        ),
        migrations.AlterField(
            model_name='category',
            name='root_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_subcategories', to='wallet.category'),
        ),
        migrations.AlterField(
            model_name='month',
            name='month_code',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, validators=[django.core.validators.RegexValidator(message='Month code must be 4 digits long', regex='^\\d{4}$'), django.core.validators.RegexValidator(code='invalid_month_code', message='Last 2 digits of month code must be between 01 and 12', regex='^\\d{2}$'), django.core.validators.RegexValidator(code='invalid_month_code', message='Last 2 digits of month code must be between 01 and 12', regex='^(0[1-9]|1[0-2])$')]),
        ),
    ]
