# Generated by Django 4.0.10 on 2023-04-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_alter_budget_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='month_days',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
