# Generated by Django 4.0.10 on 2023-04-16 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0023_month_month_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month_days',
            field=models.PositiveSmallIntegerField(default=30, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallet.category', verbose_name='Category'),
        ),
    ]
